name: repoman
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gentoo-monero/repoman-action@v1
